---
- name: Portainer
  hosts: all
  become: true

  pre_tasks:
    - name: Config
      ansible.builtin.include_vars: vars.yml

    - name: Install packages/prerequisites
      ansible.builtin.import_tasks: tasks/packages.yml

    - name: If Docker is already installed?.
      ansible.builtin.command: which docker
      failed_when: false
      changed_when: false
      check_mode: false
      register: docker_present

  tasks:
    - name: Setup Docker.
      ansible.builtin.import_tasks: tasks/docker.yml
      when: docker_present.rc == 1

    - name: Start docker
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true
      when: docker_present.rc != 1

    - name: Install portainer
      ansible.builtin.import_tasks: tasks/portainer.yml
