---

- name: Add Docker GPG apt Key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  when: ansible_facts.os_family != "RedHat"

- name: Add Docker Repository
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu jammy stable
    state: present
  when: ansible_facts.os_family != "RedHat"

- name: Update apt and install docker
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: true


- name: Add docker repo to yum
  ansible.builtin.yum_repository:
    name: docker
    description: docker yum repo
    baseurl: https://download.docker.com/linux/fedora/docker-ce.repo
  when: ansible_facts.os_family == "RedHat"

- name: Update yum cache
  ansible.builtin.dnf:
    update_cache: true
  when: ansible_facts.os_family == "RedHat"

- name: Install docker on redhat
  ansible.builtin.dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
  when: ansible_facts.os_family == "RedHat"
