---
- name: Download Docker install script.
  ansible.builtin.get_url:
    url: https://get.docker.com/
    dest: /tmp/get-docker.sh
    mode: 0775
  when: ansible_facts.os_family != "RedHat"

- name: Run Docker install script.
  ansible.builtin.command: /tmp/get-docker.sh
  failed_when: false
  changed_when: false
  check_mode: false
  environment:
    CHANNEL: stable
  when: ansible_facts.os_family != "RedHat"

- name: Add docker repo to yum
  ansible.builtin.command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  failed_when: false
  changed_when: false
  check_mode: false
  when: ansible_facts.os_family == "RedHat"

- name: Update yum cache
  ansible.builtin.dnf:
    update_cache: true
  when: ansible_facts.os_family == "RedHat"

- name: Install docker on redhat
  ansible.builtin.dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
  when: ansible_facts.os_family == "RedHat"
