
- name: Create group docker
  ansible.builtin.group:
    name: docker
    state: present

- name: Adding existing user to group sudo
  ansible.builtin.user:
    name: '{{ ansible_user }}'
    groups: docker
    append: true

- name: Reset connection
  ansible.builtin.meta: reset_connection
