---
- name: apt cache update
  apt:
    update_cache: true
    cache_valid_time: 3600
  when:
    - ansible_facts.os_family == "Debian"

- name: apt Upgrade
  apt:
    upgrade: true
  when:
    - ansible_facts.os_family == "Debian"

- name: yum cache update & upgrade
  yum:
    name: "*"
    state: latest
    update_cache: true
  when:
    - ansible_facts.os_family == "RedHat"

- name: Install packages/prerequisites "Debian"
  ansible.builtin.apt:
    name:
      - curl
      - python3-pip
      - apt-transport-https
      - ca-certificates
      - software-properties-common
      - virtualenv
      - python3-setuptools
      - gnupg
    state: present
    cache_valid_time: 3600
  when: ansible_facts.os_family == "Debian"

- name: Install packages on redhatfamily
  ansible.builtin.yum:
    name:
      - curl
      - python3
      - python3-pip
      - lvm2
      - device-mapper-persistent-data
      - yum-utils
      - device-mapper
      - device-mapper-persistent-data
      - device-mapper-event
      - device-mapper-libs
      - device-mapper-event-libs
    state: present
  when: ansible_facts.os_family == "RedHat"

- name: Install python docker SDK
  ansible.builtin.pip:
    name: docker
